version: 1.0.1.{build}
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
- cd Source
- nuget restore
- cd ..
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
after_build:
- cmd: gitlink . -c Debug
deploy:
- provider: NuGet
  server: https://www.myget.org/F/windsor-extension/api/v2/package
  api_key:
    secure: 68eb4b8b-72bb-4fae-ac48-1b60a34541da
  artifact: /.*\.nupkg/  
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cinst gitlink -y